name: Foundry CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Foundry
      run: |
        curl -L https://foundry.paradigm.xyz | bash
        foundryup

    - name: Compile contracts
      run: forge build

    - name: Run tests
      run: forge test
